services:
  ultralytics:
    pull_policy: if_not_present
    image: ultralytics/ultralytics:8.3.75
  oltralotus-base:
    pull_policy: never
    container_name: oltralotus-base
    image: alyshmahell/oltralotus:base
    build:
      context: .
      dockerfile: dockerfile.base
    depends_on:
      - ultralytics
  oltralotus:
    cpus: 4.0
    mem_limit: 4096m
    pull_policy: never
    ports:
      - "11535:11535"
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    container_name: oltralotus
    image: alyshmahell/oltralotus:latest
    runtime: nvidia
    deploy:
      mode: global
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    networks:
      - oltralotus
    depends_on:
      - oltralotus-base
networks:
  oltralotus:
    driver: bridge
